import { Toaster } from "react-hot-toast";
import "./globals.css";
import type { Metadata } from "next";
import { Locale, i18n } from "../../../i18n-config";

export const metadata: Metadata = {
  title: "Pecha Stt Tool",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  console.log("root layout params", params);
  return (
    <html lang={params.lang}>
      <body>
        {children}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
